# Generated by Django 4.2.5 on 2025-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
    ]
