# Generated by Django 4.2.5 on 2025-08-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_table', '0003_alter_infotable_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinfotable',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
